name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Add SSH private key to ssh-agent
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    # Copy files to EC2 instance
    - name: Copy files to EC2
      run: |
        scp -o StrictHostKeyChecking=no -r . ${{ secrets.USER_NAME }}@${{ secrets.HOST_IP }}:/home/${{ secrets.USER_NAME }}

    # SSH into EC2 and build/run Docker container
    - name: Deploy Docker Container
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.USER_NAME }}@${{ secrets.HOST_IP }} << 'EOF'
          cd /home/${{ secrets.USER_NAME }}
          sudo docker build -t my-app .
          sudo docker stop my-app || true
          sudo docker rm my-app || true
          sudo docker run -d --name my-app -p 80:80 my-app
        EOF
